name: notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  path_provider: ^2.1.1
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner:

flutter:
  uses-material-design: true
